// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCthTxS4eXw_SPTrh8NdQV3cvUPTjKYucg',
    appId: '1:1003069283078:web:ab3a33f0d94993104e9c87',
    messagingSenderId: '1003069283078',
    projectId: 'flutter-chat-d0a3b',
    authDomain: 'flutter-chat-d0a3b.firebaseapp.com',
    storageBucket: 'flutter-chat-d0a3b.appspot.com',
    measurementId: 'G-57L5MX9YC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqogKLU1GYtQHc26n7tNUIXyxtb3Pu1vI',
    appId: '1:1003069283078:android:49f395a72fb0b1864e9c87',
    messagingSenderId: '1003069283078',
    projectId: 'flutter-chat-d0a3b',
    storageBucket: 'flutter-chat-d0a3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6H39wiC78EdBDlp56Eqmk_Ll6-qbI9UQ',
    appId: '1:1003069283078:ios:aed9ba9501b7093c4e9c87',
    messagingSenderId: '1003069283078',
    projectId: 'flutter-chat-d0a3b',
    storageBucket: 'flutter-chat-d0a3b.appspot.com',
    iosClientId: '1003069283078-l417poch0o9bvjj7se9euaulnhd1j6s0.apps.googleusercontent.com',
    iosBundleId: 'com.badrrahmaouy-chatApp',
  );
}
